from database.mongodb import scans_collection
from database.models import create_scan_document


def save_scan(
    filename,
    original_name,
    media_type,
    filepath,
    result
):
    """
    Save a completed scan to MongoDB.
    """

    document = create_scan_document(
        filename,
        original_name,
        media_type,
        filepath,
        result
    )

    inserted = scans_collection.insert_one(document)

    return str(inserted.inserted_id)


def get_history():
    """
    Get scan history in a frontend-friendly format.
    """

    history = []

    scans = scans_collection.find().sort(
        "created_at",
        -1
    )

    for scan in scans:

        scan["_id"] = str(scan["_id"])

        # Extract analysis result
        result = scan.get("result", {})

        if not isinstance(result, dict):
            result = {}

        # Keep original database fields
        scan["result"] = result

        # Flatten important fields for frontend
        scan["media"] = (
            result.get("media")
            or scan.get("media_type")
        )

        scan["score"] = result.get(
            "score"
        )

        scan["verdict"] = result.get(
            "verdict",
            "UNKNOWN"
        )

        scan["scan_id"] = result.get(
            "scan_id",
            scan["_id"]
        )

        # Report path generated by scan.py
        if result.get("report"):
            scan["report"] = result["report"]

        history.append(scan)

    return history